name: online_prorab
description: Mobile app for construction project control.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
